package com.lovelydocs.czj.lovedocs.constants;

public class GooglePlay {
    public static final String LICENCE_KEY = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgXfFyWwdKzDfDE/dwlS3uxUCfIM3XkX6r6kNCKg7tC7pnExCG0nVmSEkvGrsF4/NGkjM/KXqgibfb+HPBjXKzB0VNLhfOOtu0DK127CxkU9eXWYjG4aAwoeVyZvWSg9PH8Svz196zTkEhpkxoXVOzhekEj0dQQwX3WIkbuJk6M/xs+FwLO74MFB5YjDHB9QXcWvjdH3VhmsJAfYepYN+dPqj8CYu8WlW0WubEPnKBJY9w/rNKK0AtwoOQl70Eyhrfv42DjDmcS1aPkg2iWywN7tqTgEP+Ql7ftHHExWmoQgL8MgRnxwWMrfVGD+88reR2bLhJmg0l5WqxFjY9oALdQIDAQAB";
    public static final String PRODUCT_ID = "lovelydocs_pro";
}
